services:
  mbs:
    image: itzg/minecraft-bedrock-server:latest
    user: $MY_UID:$MY_GID
    tty: true
    stdin_open: true
    restart: always
    container_name: $SERVER_NAME
    ports:
      - $PORT_SERVER:$PORT_SERVER/udp
    environment:
      EULA: "TRUE"
      SERVER_NAME: $SERVER_NAME
      LEVEL_NAME: $WORLD_NAME
    volumes:
      - "$DIR_SERVER:/data"
