services:
  mbs:
    image: itzg/minecraft-bedrock-server:latest
    user: $UID:$GID
    tty: true
    stdin_open: true
    restart: always
    container_name: minecraft-bedrock-server
    ports:
      - $PORT_SERVER:$PORT_SERVER/udp
    environment:
      EULA: "TRUE"
      SERVER_NAME: minecraft-bedrock-server
      LEVEL_NAME: 25nishi
    volumes:
      - "/docker/mbs:/data"
