containers:
  # Configures the containers to be backed up
  bedrock:
    - name: bedrock_public
      # The hostname here is the name of the service in the compose YML.
      ssh: public:2222
      # itzg writes out the password as yaml to the root of /data
      passwordFile: /public/.remote-console.yaml
      worlds:
        - /public/worlds
schedule:
  # Configures the schedule for backups
  daily: 11:00
  startupDelay: 1m
  onLastLogout: true
  minInterval: 3h
trim:
  # Configures how backups are 'trimmed' to save disk space
  keepDays: 30
  trimDays: 1
  minKeep: 2
