containers:
  # Configures the containers to be backed up
  bedrock:
    - name: bedrock_public
      # The hostname here is the name of the service in the compose YML.
      ssh: public:59730
      # itzg writes out the password as yaml to the root of /data
      passwordFile: /public/.remote-console.yaml
      worlds:
        - /public/worlds
schedule:
  # Configures the schedule for backups
  startupDelay: 1m
  onPlayerLogin: true
  onPlayerLogout: true
trim:
  # Configures how backups are 'trimmed' to save disk space
  keepDays: 14
  trimDays: 2
  minKeep: 2
